# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_board_development

test:
  <<: *default
  database: task_board_test

production:
  <<: *default
  database: task_board_production
  username: task_board
  password: <%= ENV['TASK_BOARD_DATABASE_PASSWORD'] %>
